"""
scripts/run_e5.py — E5: Cross-policy diagnostic (supplementary).

M[i,j] = chart i's mean UMF on chunks generated by chart j's plans.
Reports per-column argmin accuracy and saves a column-normalised heatmap.

Usage:
    python scripts/run_e5.py --charts atlas_out/e0/ln_act --out atlas_out/e5
"""

from __future__ import annotations

import argparse
from pathlib import Path

import torch
import atlas
from atlas.library import Library
from atlas.harness import build_cross_policy_matrix
from atlas.plots import crosspolicy


def main() -> None:
    parser = argparse.ArgumentParser(description="E5: Cross-policy UMF matrix.")
    parser.add_argument("--charts", type=Path, required=True,
                        help="Directory with chart .pt files from E0.")
    parser.add_argument("--out", type=Path, default=atlas.OUT_DIR / "e5")
    args = parser.parse_args()

    print("Loading dino_wm_pusht...")
    model, prep = torch.hub.load(
        "facebookresearch/jepa-wms", "dino_wm_pusht",
        force_reload=False, trust_repo=True,
    )
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)
    for p in model.encoder.parameters():
        p.requires_grad_(False)
    for p in model.predictor.parameters():
        p.requires_grad_(False)

    library = Library.load(args.charts, model.predictor)
    print(f"Library: {library}")

    raise NotImplementedError(
        "run_e5.py: collect chunks_per_chart by running each chart's plan for a few episodes.\n"
        "chunks_per_chart[j] = list of {encoder_output, actions} dicts from episodes where chart j was active.\n"
        "Then call:\n"
        "    M = harness.build_cross_policy_matrix(library, model.predictor, chunks_per_chart, motion_gate)\n"
        "    plots.crosspolicy(M.numpy(), chart_labels, args.out / 'F_crosspolicy.pdf')\n"
        "Report per-column argmin accuracy: for each column j, is argmin_i M[i,j] == j?"
    )


if __name__ == "__main__":
    main()
