"""
harness.py — Offline evaluation harness for E0, E1, E5.

E0 (adapter capacity):
  - Fine-tune chart kinds offline on regime trajectories.
  - Evaluate UMF and planning success in-regime.

E1 (fitness routing):
  - Charts fixed; 2 warmup replans under c₀, then route and plan.
  - Same seeds across all routers (G5 guaranteed by streams.paired_seed).

E5 (cross-policy):
  - M[i,j] = chart i's UMF on chunks from chart j's plans.

All harness functions write per-episode JSONL to the output directory.
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

import torch

from atlas.chart import Chart, ChartKind
from atlas.library import Library
from atlas.score import umf as compute_umf
from atlas.router import route, RouterKind
from atlas import LOGS_DIR


# ── E0 — Adapter capacity ─────────────────────────────────────────────────────

def run_e0_finetune(
    predictor,
    encoder,
    trajectories: list[dict],   # list of {encoder_output, actions} dicts
    kind: ChartKind,
    regime: str,
    n_steps: int,
    lr: float,
    out_dir: Path,
) -> Chart:
    """
    Offline fine-tune a chart of the given kind on provided trajectories.

    Args:
        predictor:    Frozen JEPA predictor.
        encoder:      Frozen DINOv2 encoder.
        trajectories: List of trajectory dicts with pre-encoded data.
        kind:         Chart kind to fine-tune.
        regime:       Regime name (for logging).
        n_steps:      Number of gradient steps.
        lr:           Learning rate.
        out_dir:      Directory to save the resulting chart and loss log.

    Returns:
        The fine-tuned Chart.
    """
    import torch.optim as optim

    out_dir.mkdir(parents=True, exist_ok=True)
    chart = Chart(predictor, kind)
    chart.apply_(predictor)
    params = [p for n, p in predictor.named_parameters() if n in chart._param_names]
    optimizer = optim.Adam(params, lr=lr)

    loss_log: list[float] = []
    for step in range(n_steps):
        optimizer.zero_grad()
        total_loss = torch.tensor(0.0)
        for traj in trajectories:
            enc_out: torch.Tensor = traj["encoder_output"]
            actions: torch.Tensor = traj["actions"]
            T = actions.shape[0]
            z_cur = enc_out[0].unsqueeze(0)
            loss = torch.tensor(0.0, device=z_cur.device)
            for t in range(T):
                a_t = actions[t].unsqueeze(0)
                z_next_hat = predictor(z_cur, a_t)
                loss = loss + (z_next_hat - enc_out[t + 1].unsqueeze(0)).pow(2).mean()
                z_cur = z_next_hat.detach()
            total_loss = total_loss + loss / T
        (total_loss / len(trajectories)).backward()
        optimizer.step()
        loss_log.append(total_loss.item() / len(trajectories))

    chart.update_from_predictor_(predictor)
    chart.restore_(predictor)

    chart_path = out_dir / f"chart_{kind}_{regime}.pt"
    chart.save(chart_path)
    (out_dir / f"loss_{kind}_{regime}.json").write_text(json.dumps(loss_log))
    return chart


# ── E1 — Fitness routing ──────────────────────────────────────────────────────

def run_e1_episode(
    library: Library,
    predictor,
    encoder,
    env,
    router: RouterKind,
    episode_seed: int,
    n_warmup_replans: int,
    motion_gate: float | None,
    hysteresis: float,
    out_dir: Path,
    episode_id: str,
    *,
    regime_label: int | None = None,
    label_to_chart: dict[int, int] | None = None,
) -> dict[str, Any]:
    """
    Run one E1 episode with a specified router.

    Warmup: 2 replans under c₀. Then route using *router* for the rest.
    Returns per-episode metrics dict (also written to JSONL).

    This function is a HARNESS STUB — the actual planning loop depends on
    the jepa-wms CEM planner API. The caller must integrate this with the
    upstream planning eval code from jepa-wms. See scripts/run_e1.py for
    the integration point.
    """
    raise NotImplementedError(
        "run_e1_episode() is an integration stub. "
        "Wire this into the jepa-wms planning eval loop in scripts/run_e1.py. "
        "See the implementation plan §7.2 for the required episode structure."
    )


# ── E5 — Cross-policy matrix ──────────────────────────────────────────────────

def build_cross_policy_matrix(
    library: Library,
    predictor,
    chunks_per_chart: list[list[dict]],   # chunks_per_chart[j] = chunks from chart j's plans
    motion_gate: float | None,
) -> torch.Tensor:
    """
    Compute M[i,j] = chart i's mean UMF on chunks generated by chart j's plans.

    Args:
        library:          Chart library with K charts.
        predictor:        Frozen JEPA predictor.
        chunks_per_chart: List of K lists; chunks_per_chart[j] are the encoded
                          chunks collected while chart j was active.
        motion_gate:      Informative-chunk gate.

    Returns:
        [K, K] matrix of mean UMF values (NaN where all chunks are gated).
    """
    K = len(library)
    if len(chunks_per_chart) != K:
        raise ValueError(
            f"chunks_per_chart has {len(chunks_per_chart)} entries but library has {K} charts."
        )
    M = torch.full((K, K), float("nan"))
    for i, chart_i in enumerate(library):
        for j, chunk_list in enumerate(chunks_per_chart):
            scores = []
            for chunk in chunk_list:
                s = compute_umf(chart_i, predictor,
                                chunk["encoder_output"], chunk["actions"], motion_gate)
                if s is not None:
                    scores.append(s)
            if scores:
                M[i, j] = sum(scores) / len(scores)
    return M


# ── JSONL logging ─────────────────────────────────────────────────────────────

def log_episode(out_dir: Path, record: dict) -> None:
    """Append one episode record to a JSONL log file."""
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_dir / "episodes.jsonl", "a") as f:
        f.write(json.dumps(record) + "\n")
